INSERT INTO member VALUES
(1, 'Cory', 'L', 'Wandling'),
(2, 'Rhonda', 'K', 'Wandling'),
(3, 'Kyle', 'M', 'Wandling'),
(4, 'Robert', 'M', 'Wandling'),
(5, 'Cherie', 'F', 'Wandling'),
(6, 'Stephanie', 'F', 'Wandling'),
(7, 'Emily', 'B', 'Wandling'),
(8, 'James', 'C', 'Wandling'),
(9, 'Marjorie', 'B', 'Wandling'),
(10, 'Nathaniel', 'L', 'Wandling'),
(11, 'Tina', 'D', 'Wandling'),
(12, 'Aaron', 'J', 'Wandling')
